### ISSUE TITLE
Allow intervals longer than 255 milliseconds

### ISSUE THREAD

**Issue by threadlock** [Killeroo/PowerPing#117]
It would really be nice if I could specify intervals longer than 255 milliseconds.  I'm trying to log intermittent latency spikes from my ISP and I only need a ping every 5-10 seconds or so.

**Comment by Killeroo** [comment]
Have you tried using the interval option (```--interval or -in```)? That lets you specify the amount of milliseconds between pings and there is no upper limit so sounds like what you are looking for?

**Comment by threadlock** [comment]
Yes, that's what I tried at first.  When I try to set the interval to 10000 I get this error message:

Bad value for option -in, valid range is from 1 to 255.

**Comment by threadlock** [comment]
Nevermind, I'm an idiot.  I thought I was using PowerPing but I was actually using the built-in ping.  Your app is working as expected.  Thank you for this very useful utility.

**Comment by Killeroo** [comment]
No problem :) glad I could help
