### ISSUE TITLE
-fts output with ms, not s

### ISSUE THREAD

**Issue by stratege1401** [Killeroo/PowerPing#118]
Hello,

is it possible to have the output of -fts parameter shown in ms, not s

actually, having 
```
PowerPing -t -fts -in 500 google.fr

Pinging google.fr [216.58.215.35] with 35 bytes of data [Type=8 Code=0] [TTL=255]:
Reply from: 216.58.215.35:0 seq=1 bytes=63 type=ECHO REPLY time=14,0ms @ 22/10/2020 19:39:42
Reply from: 216.58.215.35:0 seq=2 bytes=63 type=ECHO REPLY time=14,4ms @ 22/10/2020 19:39:42
Reply from: 216.58.215.35:0 seq=3 bytes=63 type=ECHO REPLY time=14,2ms @ 22/10/2020 19:39:43
```
Would like to have 19:39:42.003 19:39:42.603  ...

**Comment by Killeroo** [comment]
I've added milliseconds to the full timestamp argument. Should be included in the next release.

**Comment by stratege1401** [comment]
Great. Thank you.

**Comment by Killeroo** [comment]
This has been added in the [latest release](https://github.com/Killeroo/PowerPing/releases/latest).
