### ISSUE TITLE
the Message  buf should be larger than 65536

### ISSUE THREAD

**Issue by ColdwindY** [Killeroo/PowerPing#119]
the Message  buf should be larger than 65536,otherwise if -s 2000 then System.ArgumentException.
The max ICMP pkg is 65536. So just set 
public byte[] Message = new byte[80000]; 
at line 39,ICMP.cs

**Comment by Killeroo** [comment]
Thanks for pointing this out. Yeah this seems to be a bug with the way that we are updating the ICMP message field, will submit a fix soon.

**Comment by Killeroo** [comment]
This should be fixed in the lasted release, you can [download it here](https://github.com/Killeroo/PowerPing/releases/latest).

**Comment by Killeroo** [comment]
RecieveBuffer is now set to max ICMP size, closing this for now 👍
