### ISSUE TITLE
How to install in ubuntu

### ISSUE THREAD

**Issue by pedritojp** [Killeroo/PowerPing#122]
I want to know how I can do to install on linux

**Comment by Killeroo** [comment]
In the current version of PowerPing only Windows is supported. But in the next major release I should have the ability to release some builds for other platforms, you can track the progress of that task here: https://github.com/Killeroo/PowerPing/projects/4#card-83184317

**Comment by Killeroo** [comment]
I have shipped an experimental x64 linux build with the lastest version. You can find it here: https://github.com/Killeroo/PowerPing/releases/tag/v1.3.4
