### ISSUE TITLE
Typo: "Recieved" -> "Received"

### ISSUE THREAD

**Issue by RaffaeleBianc0** [Killeroo/PowerPing#124]
Typo: "Recieved" -> "Received"
![image](https://user-images.githubusercontent.com/12746830/219415927-43c5c103-db7b-4091-87a9-4252f2ddd477.png)

**Comment by Killeroo** [comment]
Thanks for pointing this out 👍 I'll track this for the next release

**Comment by Killeroo** [comment]
This has now been included in the lastest release. Thanks again.
