### ISSUE TITLE
Some ICMP packets cause ArgumentException in listen mode

### ISSUE THREAD

**Issue by steom** [Killeroo/PowerPing#127]
some icmp pattern cause crash.. fyi

Unhandled Exception: System.ArgumentException: Offset and length exceed the bounds of the array, or the count is greater than the number of elements from the index to the end of the source collection.
   in System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   in PowerPing.ICMP..ctor(Byte[] data, Int32 size)
   in PowerPing.Listen.ListenForICMPOnAddress(IPAddress address)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()

**Comment by Killeroo** [comment]
Thanks for reporting 👍

**Comment by Killeroo** [comment]
I've added a speculative fix that should stop this from happening in the [latest release](https://github.com/Killeroo/PowerPing/releases/latest). Please let me know if it keeps occuring.
