### ISSUE TITLE
How do I save the results to a file?

### ISSUE THREAD

**Issue by paolosezart** [Killeroo/PowerPing#128]
How do I enter the correct command to save the results to a file?
In general, in what order should they be entered?

I tried to scan my network, but I can't save the results:

![Screen](https://github.com/Killeroo/PowerPing/assets/38177890/3c5860ba-c375-407a-be48-cc0c81826b05)

The results are only in the CMD output window.

**Comment by Killeroo** [comment]
The `--scan` argument doesn't currently support writing the results to a file using `--log`. I can look into fixing this for the next release.

**Comment by paolosezart** [comment]
> I can look into fixing this for the next release.

Is the respected developer going to update the program?

**Comment by Killeroo** [comment]
> > I can look into fixing this for the next release.
> 
> Is the respected developer going to update the program?

Apologies I have been extremely busy recently. I intend to release a pre-release version of PowerPing addressing issues like this soon.

**Comment by Killeroo** [comment]
This should be fixed in latest, you can download it here: https://github.com/Killeroo/PowerPing/releases/latest

**Comment by Killeroo** [comment]
Closing this as `--log` command should now work correctly with the `--scan` command
