### ISSUE TITLE
--b --ping does not seem to work as intended...

### ISSUE THREAD

**Issue by DesktopMasters** [Killeroo/PowerPing#130]
It seems like you would do "--b 1" if you want it to beep on timeouts and "--b 2" if you want it to beep on replies.  But it --b 2 also beeps on "HOST UNREACHABLE"...  when really --b 1 should beep if it is unreachable.  This makes the tool not useful if you are wanting to be notified when a host comes on-line.

**Comment by Killeroo** [comment]
Thanks for pointing this out. I'll get this fixed for the next release 👍

**Comment by Killeroo** [comment]
I've fixed this in the lastest release, you can [download it here](https://github.com/Killeroo/PowerPing/releases/latest). Thanks again for pointing this out.

**Comment by DesktopMasters** [comment]
👍

**Comment by Killeroo** [comment]
I'm closing this as the original issue as described by your first comment has been addressed 👍
