### ISSUE TITLE
feature request: latency threshhold and summary of high latency

### ISSUE THREAD

**Issue by p1r473** [Killeroo/PowerPing#133]
High latency can mean different things for different people
For a gamer it could be 200ms
For an office worker maybe its 1000ms
Can you make a threshhold where we can say what # of latency produces a "red" colored result? 
Also, the summary should include how many packets were high latency in this threshhold

**Comment by Killeroo** [comment]
Cool feature idea. I'll track it for the next release.

**Comment by Killeroo** [comment]
I've added new commands (`--low`, `--mid` and `--high`) that let you define the thresholds used for colouring response times. 

You should be able to find it in the latest release, you can find [download it here.](https://github.com/Killeroo/PowerPing/releases/latest)

**Comment by p1r473** [comment]
Awesome ty
