### ISSUE TITLE
JUMBO FRAME SUPPORT

### ISSUE THREAD

**Issue by DCNESS1213** [Killeroo/PowerPing#137]
can this be used to support jumbo frame up to 9600.

**Comment by Killeroo** [comment]
Depending on your network setup then yes. You can send a ping that is over 9600 bytes using PowerPing but ultimately it is up to your network adapter if that will be sent as a jumbo frame, PowerPing cannot affect how the data is actually transmitted.

**Comment by DCNESS1213** [comment]
im try to use this syntax but not able to send the ping due to an error. Am i doing it right or there is another way to set the Frame size.

c:\>powerping 8.8.8.8 -s 1500 -ti 6 -sym 1 -c 1000

![image](https://github.com/Killeroo/PowerPing/assets/162288763/62f32c49-2eab-4da1-afa3-af4c22f3cdd7)

**Comment by Killeroo** [comment]
Ah yes this does seem to be a PowerPing bug, it's been reported before (https://github.com/Killeroo/PowerPing/issues/119). I will look to get this fixed soon, thanks for reporting.

**Comment by Killeroo** [comment]
I've fixed this bug and you should be able to send a ping of over 1500 bytes in the latest release (you can [download it here](https://github.com/Killeroo/PowerPing/releases/latest)).

Just any FYI, in testing I found that 8.8.8.8 won't reply to any pings bigger than 1000 bytes :) But I did verify that the full 1500 bytes are getting sent on the wire.

**Comment by DCNESS1213** [comment]
Thanks sir i tried this just now. 

Just sending ping to my router(Cisco 8200)

![image](https://github.com/Killeroo/PowerPing/assets/162288763/6cbb531e-34e9-4879-ab27-20b39d40ff9b)

**Comment by Killeroo** [comment]
Found an issue with parsing the returned packet, thanks for reporting this. Will update the release later today 👍

**Comment by DCNESS1213** [comment]
thanks sir, i appreciate the work you put in to this

**Comment by Killeroo** [comment]
No worries, I've updated the latest release now. Try it out, that should fix the exception you were seeing.

**Comment by DCNESS1213** [comment]
Thanks will try it now. looks great

**Comment by DCNESS1213** [comment]
everything in order. Thanks
