### ISSUE TITLE
Fix Control C event handler

### ISSUE THREAD

**Issue by Killeroo** [Killeroo/PowerPing#34]
Event C handler currently not working properly, works with delay/lag

Responsiveness tested in:
- _Sending Normally_ (requires more testing)
- Graph
- _Flood_  (requires more testing)
- Scan

**Comment by Killeroo** [comment]
Clean up readme remove 'address' after arguments

**Comment by Killeroo** [comment]
Starting some operations in new threads (https://github.com/Killeroo/PowerPing/commit/3793f7872f503ce32ff8b79d18895de10d53a6a9) has helped control c responsiveness.

Some further improvements could be made to CancelEvent flag handling and threading changes should be propagated to other features (graph, scan etc), but so far I am happy with improvement.

Will keep testing changes for the next few days and close if performance remains satisfactory (especially with pinging address for multiple hours)

**Comment by Killeroo** [comment]
![image](https://user-images.githubusercontent.com/9999745/35594144-06261f06-060a-11e8-9891-d092c3c8ffc6.png)
Major performance problems, thread not exciting immediately (use 10 ssecond time out)

**Comment by Killeroo** [comment]
Fixed performance issues (https://github.com/Killeroo/PowerPing/commit/db185c18c6875104ab6d00a51c7bd6e25a65e486) but needs control-c event to override set timeout on socket

**Comment by jdpurcell** [comment]
@Killeroo I fixed the delay everywhere; I'll submit a pull request after my other one is merged (to avoid conflicts).

**Comment by jdpurcell** [comment]
I'd also like to know if it fixes all the delays you're aware of. The one that was bugging me was when stopping the graph; I spent probably an hour debugging it and almost couldn't figure out where it was hanging. I'm pretty sure that was due to the thread there having IsBackground = true, although I have no explanation as to why that would cause it.

**Comment by Killeroo** [comment]
@jdpurcell Had a look at that branch, very interesting. I'll run a copy of it over the next few days and see how it does. (My main irritation was how the control-c event would be delayed when using different timing options)

To be honest I wouldn't have thought to use this approach, I'm not 100% famailiar with some of the timespan and cancellation specific stuff you are using (but I will endevour to do some research in the meantime). The problem has been so persistent across features for so long (to the point that I feel it really affects usability) that I am more than open to discussing going down this route.

Test and work on it as much as you need and then when you open a PR we can go through it properly.

**Comment by jdpurcell** [comment]
@Killeroo I'd say the branch is pretty stable at this point; I finished some more testing last night and pushed some minor changes (warning: I often to amend commits + force pushes when I work on my own branch). I just wanted to play around with the BeginReceiveFrom stuff a little bit more to satisfy my curiosity before I call it done.

**Comment by Killeroo** [comment]
@jdpurcell Thats absolutely fine, I've built a copy of your branch that I will use tomorrow just to initially test the fix out.
