### ISSUE TITLE
Ping time defaults to 0.1ms

### ISSUE THREAD

**Issue by Killeroo** [Killeroo/PowerPing#57]
# Behavior:
- Starts when error or other packet type is received
- Normally occurs when when data is recieved from other address than that being actively pinged (eg hub addresses like 192.168.1.255 etc)
- Also occurs when another PowerPing instance starts pinging same target
- Does not occur due to timeout

**Could be caused by responseTime.Restart(), [MSDN page](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.restart(v=vs.105).aspx) states 'resets the elapsed time to zero, and _starts measuring elapsed time_.' could be prematurely starting stopwatch..**

# Solutions
- ~~Could be due to StopWatch object not resetting properly in final clause (Ping.cs: line 404), could use [StartNew (maybe not...)](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.startnew(v=vs.110).aspx) or [Reset (maybe not either..)](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.reset(v=vs.110).aspx) instead of restart.~~
- Alternatively could use [Timer class](https://msdn.microsoft.com/en-us/library/system.timers.timer(v=vs.110).aspx) for some more low level control, utilizing its [.interval](https://msdn.microsoft.com/en-us/library/system.timers.timer.interval(v=vs.110).aspx) method. HOWEVER there could be concerns here about accuracy
- ~~[Could be how we are using timespan in display.cs?](https://stackoverflow.com/a/19589326) (Spoilers I think Display uses DateTime not timespan)~~
- Could possibly use raw StopWatch data to get more accurate readings, rather than using methods as shown [here](https://www.codeproject.com/Tips/162553/How-To-Measure-execution-time-in-C) and [also here](https://www.codeproject.com/Articles/98346/Microsecond-and-Millisecond-NET-Timer)

# Todo

- [x] ~~Add feature to specifiy level of detail with time (decimal 1.23 or just 1 ms)~~
- [x] ~~Implement more accurate and safe time management or look into way of isolating PowerPings properties or resources being used in other instances. [Good article on good .NET practices, mentions app domains and how the code is structured on a low level](https://msdn.microsoft.com/en-us/library/ms973839.aspx) and [Another good one relating more to performance](https://msdn.microsoft.com/en-us/library/ms973838.aspx)~~

# Links
- [Article examining the accuracy of different timing methods across platforms](http://aakinshin.net/blog/post/stopwatch/)

**Comment by Killeroo** [comment]
Also seems to happen after an error packet is received:

![image](https://user-images.githubusercontent.com/9999745/31601534-13b56e4e-b252-11e7-8da4-e368864e4dd6.png)

**Comment by Killeroo** [comment]
Could be due to StopWatch object not resetting properly in final clause (Ping.cs: line 404), could use [StartNew](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.startnew(v=vs.110).aspx) or [Reset (maybe not..)](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.reset(v=vs.110).aspx) instead of restart. 

Alternatively could use [Timer class](https://msdn.microsoft.com/en-us/library/system.timers.timer(v=vs.110).aspx) for some more low level control

Need to work out the conditions that this bug occurs, general behavior is:
- Starts when error or other packet type is received
- Normally occurs when when data is recieved from other address than that being actively pinged (eg hub addresses like 192.168.1.255 etc)
- Also occurs when another PowerPing instance starts pinging same target
- Does not occur due to timeout

Todo

- Add feature to specifiy level of detail with time (decimal 1.23 or just 1 ms)
- Look into way of isolating PowerPings properties or resources being used in other instances

**Comment by Killeroo** [comment]
Found a way to replicate low timer value, at this commit https://github.com/Killeroo/PowerPing/commit/52c8069209fbc7595e2966e0555e51395f8bbc45 when using graph mode, the timer always gives a value lower than 1ms. Should be used to try and debug the problem

**Comment by Killeroo** [comment]
![image](https://user-images.githubusercontent.com/9999745/41431131-e4b88344-7009-11e8-8c07-7dc1505f21b3.png)

Timer seems to correct when response time over 100ms occurs, maybe find a way of replicating?

**Comment by jdpurcell** [comment]
@Killeroo Maybe not a timing issue but rather extra packets getting queued up in the receive buffer? For example if you have 2 instances pinging the same address with different messages (use -m and -dm), the first instance displays both messages, not just its own.

**Comment by jdpurcell** [comment]
@Killeroo Without being too familiar with the code it's hard to say, but I'd think something like including a unique value per instance (e.g. a random number generated on startup or Process.GetCurrentProcess().Id), or even a unique value per packet (e.g. random number, sequence number, Guid) if necessary.

**Comment by Killeroo** [comment]
@jdpurcell A unique value per packet definitely makes sense, then we could have some sort of list or map to link the unique value to a packet sequence number and timestamp. It could be inserted before any text from --messages. Yeah sounds promising, I think I'll do some experimentation with it whenever I get a chance.
