### ISSUE TITLE
Improve graph command

### ISSUE THREAD

**Issue by Killeroo** [Killeroo/PowerPing#97]
- [ ] Improve refresh rate of bars (stop that flashing)
- [x] Add border and maybe some [colours?](https://github.com/amanusk/s-tui)

**Comment by masgo** [comment]
Another idea would be to be able to change the y-Axis. Either to logarithmical, to a custom max value or dynamically. Right now, changes in fast networks (e.g., LAN) are hard to see.

**Comment by Killeroo** [comment]
I've added graph auto scaling and other improvements to the most recent release (https://github.com/Killeroo/PowerPing/releases/tag/v1.3.1). Closing this ticker for now, thank you for the suggestion @masgo
